name = "WearRateDistributions"
uuid = "3a55a41c-b17d-44d7-981a-fbe088e2d8c8"
authors = ["Ruben Gonzalez <ruben.carbonbased@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
