include(joinpath(@__DIR__,"_SignedGamma.jl"))
include(joinpath(@__DIR__,"_ShiftedGamma.jl"))
include(joinpath(@__DIR__,"_Polynomial.jl"))
include(joinpath(@__DIR__,"_SplineSamples.jl"))
include(joinpath(@__DIR__,"_CubicSpline.jl"))
